Book
GRDigital/hobo pull request #12
Opened 2022-10-18 15:40 UTC by Gremious

2022-10-18 16:47 UTC, Awpteamoose requested changes
Keep in mind that `hobo::SomeElement` is now just `hobo::Element` (same as old `Element` is now `AsElement`, which mirrors `Entity`/`AsEntity`) - you'll have to fix up code examples.

This is only a preliminary review, I'll build the book and do a more thorough one tomorrow.

2022-10-18 16:47 UTC, Awpteamoose commented on README.md
> +**STILL WIP** although used in production by [GR Digital](https://grdigital.co.uk/).
these empty lines are importantm otherwise `**STILL WIP**` doesn't get moved on the next line

2022-10-18 16:47 UTC, Awpteamoose commented on README.md
> +		)
tabs show up as 8-width in mdbook and there's no way to change that soooo all code examples should use 4 spaces for idents

2022-10-18 16:47 UTC, Awpteamoose commented on book/src/basic-concepts/borrowing-and-storage.md
> +mod example_module {
unnecessary mod?

2022-10-18 16:47 UTC, Awpteamoose commented on book/src/utilities/events.md
> -// -- snip --
this was to show that there's an unspecified amount of code between the event definition and its use, idk maybe it wasn't important

2022-10-18 16:47 UTC, Awpteamoose commented on book/src/basic-concepts/borrowing-and-storage.md
> +```
I'd add to this chapter the common cases where this happens - namely deleting entities while holding a storage or futures that hold onto a storage while some code elsewhere tries to get it (e.g. to delete an entity or smth else)

also, you don't need to `std::mem::`, just `drop` works

2022-10-18 16:47 UTC, Awpteamoose commented on book/src/state/queries.md
> +Queries are tuples of `& T`, `&mut T` or `With<T>` where `T` is some component or, as a special case, `Entity`. The result of `hobo::find` (or `hobo::find_one`) are tuples where each member is what w
you should still specify that `With<T>` will insert a value that should be ignored, it might be a surprise/gotcha otherwise

2022-10-20 13:06 UTC, Awpteamoose requested changes
Misc notes:
* in hobo::create chapter, `type that implements Element` -> `type that implements AsElement`
* in hobo::create chapter, `fn content() -> impl hobo::Element` -> `fn content() -> impl hobo::AsElement`
* @-rules chapter, docs link to @font-face needs to  be updated (probably for 0.3 version which this will be released as)
* @-rules chapter, escape hatch raw string needs an example
* Every way to make a class chapter, could use an example for each of those
* There's probably some Recipes that we could add, I'll have a think

2022-10-20 13:34 UTC, Gremious commented on book/src/basic-concepts/borrowing-and-storage.md
> +Components for entities are stored in a simple map - `HashMap<Entity, Component>` (see, `hobo::storage`).
I feel like it's relatively simple info to digest, and useful context to know to make sense of the rest of this chapter.

Cause the first question I'd have if i read "we are borrowing storage" is "what am i borrowing what is storage"
So knowing it's a map i can kinda conceptualise get_cmp as just getting a hash_map ref
idk if that's necessarily *correct* though?

2022-10-21 14:22 UTC, Awpteamoose approved these changes

2022-10-21 14:23 UTC, merged